/*
 * Pedellus API
 *
 * A NetAcademia szolgáltatásainak API-ja
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Recording :  IEquatable<Recording>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Recording" /> class.
        /// </summary>
        /// <param name="Id">Id.</param>
        /// <param name="ChannelName">ChannelName.</param>
        /// <param name="ViewerCount">ViewerCount.</param>
        /// <param name="HasRecorder">HasRecorder.</param>
        /// <param name="HasStream">HasStream.</param>
        public Recording(Guid? Id = null, Guid? ChannelName = null, int? ViewerCount = null, bool? HasRecorder = null, bool? HasStream = null)
        {
            this.Id = Id;
            this.ChannelName = ChannelName;
            this.ViewerCount = ViewerCount;
            this.HasRecorder = HasRecorder;
            this.HasStream = HasStream;
            
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// Gets or Sets ChannelName
        /// </summary>
        [DataMember(Name="channelName")]
        public Guid? ChannelName { get; set; }

        /// <summary>
        /// Gets or Sets ViewerCount
        /// </summary>
        [DataMember(Name="viewerCount")]
        public int? ViewerCount { get; set; }

        /// <summary>
        /// Gets or Sets HasRecorder
        /// </summary>
        [DataMember(Name="hasRecorder")]
        public bool? HasRecorder { get; set; }

        /// <summary>
        /// Gets or Sets HasStream
        /// </summary>
        [DataMember(Name="hasStream")]
        public bool? HasStream { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Recording {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ChannelName: ").Append(ChannelName).Append("\n");
            sb.Append("  ViewerCount: ").Append(ViewerCount).Append("\n");
            sb.Append("  HasRecorder: ").Append(HasRecorder).Append("\n");
            sb.Append("  HasStream: ").Append(HasStream).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((Recording)obj);
        }

        /// <summary>
        /// Returns true if Recording instances are equal
        /// </summary>
        /// <param name="other">Instance of Recording to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Recording other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.ChannelName == other.ChannelName ||
                    this.ChannelName != null &&
                    this.ChannelName.Equals(other.ChannelName)
                ) && 
                (
                    this.ViewerCount == other.ViewerCount ||
                    this.ViewerCount != null &&
                    this.ViewerCount.Equals(other.ViewerCount)
                ) && 
                (
                    this.HasRecorder == other.HasRecorder ||
                    this.HasRecorder != null &&
                    this.HasRecorder.Equals(other.HasRecorder)
                ) && 
                (
                    this.HasStream == other.HasStream ||
                    this.HasStream != null &&
                    this.HasStream.Equals(other.HasStream)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.ChannelName != null)
                    hash = hash * 59 + this.ChannelName.GetHashCode();
                if (this.ViewerCount != null)
                    hash = hash * 59 + this.ViewerCount.GetHashCode();
                if (this.HasRecorder != null)
                    hash = hash * 59 + this.HasRecorder.GetHashCode();
                if (this.HasStream != null)
                    hash = hash * 59 + this.HasStream.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(Recording left, Recording right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Recording left, Recording right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
