/*
 * Pedellus API
 *
 * A NetAcademia szolgáltatásainak API-ja
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class RecordingDetails :  IEquatable<RecordingDetails>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RecordingDetails" /> class.
        /// </summary>
        /// <param name="Title">Title.</param>
        /// <param name="Modul">Modul.</param>
        /// <param name="HasToKeep">HasToKeep.</param>
        public RecordingDetails(string Title = null, Guid? Modul = null, bool? HasToKeep = null)
        {
            this.Title = Title;
            this.Modul = Modul;
            this.HasToKeep = HasToKeep;
            
        }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name="title")]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets Modul
        /// </summary>
        [DataMember(Name="modul")]
        public Guid? Modul { get; set; }

        /// <summary>
        /// Gets or Sets HasToKeep
        /// </summary>
        [DataMember(Name="hasToKeep")]
        public bool? HasToKeep { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RecordingDetails {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Modul: ").Append(Modul).Append("\n");
            sb.Append("  HasToKeep: ").Append(HasToKeep).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((RecordingDetails)obj);
        }

        /// <summary>
        /// Returns true if RecordingDetails instances are equal
        /// </summary>
        /// <param name="other">Instance of RecordingDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RecordingDetails other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Title == other.Title ||
                    this.Title != null &&
                    this.Title.Equals(other.Title)
                ) && 
                (
                    this.Modul == other.Modul ||
                    this.Modul != null &&
                    this.Modul.Equals(other.Modul)
                ) && 
                (
                    this.HasToKeep == other.HasToKeep ||
                    this.HasToKeep != null &&
                    this.HasToKeep.Equals(other.HasToKeep)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Title != null)
                    hash = hash * 59 + this.Title.GetHashCode();
                if (this.Modul != null)
                    hash = hash * 59 + this.Modul.GetHashCode();
                if (this.HasToKeep != null)
                    hash = hash * 59 + this.HasToKeep.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(RecordingDetails left, RecordingDetails right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RecordingDetails left, RecordingDetails right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
